### ISSUE TITLE
Data is not synchronized between the server and the client.

### ISSUE THREAD

**Issue by csthenry** [AOMIAOMAO/BarbequesDelight#2]
In online mode, the things on the grill, the ingredients basin, sometimes you can't see what others have put on it, has anyone encountered 1.20.1 fabric.
In short, there is a synchronization problem between the server and the client, such as someone else has taken the skewer and someone else can see the skewer is still on the grill (or even burned).

**Comment by AOMIAOMAO** [comment]
It's a bit hard for me to fix it and I need a bit of time to do so

**Comment by AOMIAOMAO** [comment]
I've fixed it.
