### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by Copy-TT** [AOMIAOMAO/BarbequesDelight#3]
[ko_kr.json](https://github.com/user-attachments/files/15904625/ko_kr.json)

**Comment by AOMIAOMAO** [comment]
Mod has been updated to 1.0.5

**Comment by AOMIAOMAO** [comment]
Please update your translations to the current version of the mod.

**Comment by Copy-TT** [comment]
[ko_kr.json](https://github.com/user-attachments/files/16047325/ko_kr.json)
