### ISSUE TITLE
1.20.1 Fabric - Mod doesn't work on server

### ISSUE THREAD

**Issue by Dumpling00** [AOMIAOMAO/BarbequesDelight#4]
![image](https://github.com/AOMIAOMAO/BarbequesDelight/assets/44829013/5450c6ef-4bf7-4301-882b-5110b82406bd)

Hey there! Would really love to use this mod on my server but I'm getting this issue for some reason, and the server refuses to start. Guessing it's an incompatibility with the loader version?
Is there any chance we could have a fix?

Thank you for your time and consideration.

**Comment by csthenry** [comment]
I have this problem

**Comment by AOMIAOMAO** [comment]
Well, this is actually caused by your loader version being too low

**Comment by AOMIAOMAO** [comment]
Well, this is actually caused by your loader version being too low, however, I will be lowering the loader version required for the mod in version 1.0.7

**Comment by csthenry** [comment]
> I have this problem

but, my fabric is the latest version for mc1.20.1, and other mods are working, I still feel that this is a mod issue. 

you said "loader version" means?

**Comment by csthenry** [comment]
@AOMIAOMAO but, my fabric is the latest version for mc1.20.1, and other mods are working, I still feel that this is a mod issue.

you said "loader version" means?

**Comment by AOMIAOMAO** [comment]
Sorry, it's actually an error in the tooltip event

**Comment by AOMIAOMAO** [comment]
1.0.7 has been resolved [1.0.7](https://modrinth.com/mod/barbeques-delight/version/1.0.7)

**Comment by AOMIAOMAO** [comment]
1.0.7 已解决 [1.0.7](https://modrinth.com/mod/barbeques-delight/version/1.0.7) @csthenry
